spring:
  datasource:
     generate-unique-name: false # Spring to not generate a unique random for the database name . Instead,
                                 # it should use the value set to the spring.datasource.name property
     name: tacocloud             # url database is jdbc:h2:mem:tacocloud
