server:
  port: 8080  #Spring cambio de puerto 

logging:
  level:
    tacos: debug  


taco:
  orders:
    pageSize: 15


           
spring:
  datasource:
     generate-unique-name: false # Spring to not generate a unique random for the database name . Instead,
                                 # it should use the value set to the spring.datasource.name property
     name: tacocloud             # url database is jdbc:h2:mem:tacocloud
  data:
   rest:
      base-path: /data-api

# Creación de profile de producción para activarlo pude activarlo
# activarlo agregando la variable de ambiente spring.profiles.active=prod de variable de ambiente
# en el ide
---
spring:
  config:
   activate:
      on-profile:
      - prod   
   
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: warn 


 


   

  
    
